#!/bin/node
import cmd from "../../../scripts/cmd.js";

const characters = ["ó", "ö", "ő", "ü", "ű", "ú", "é", "ë", "í", "á", "ä", "ß", "ç", "ɶ"].join("\n");

const capitalCharacters = characters
	.split("\n")
	.filter((ch) => ch !== "ß")
	.map((c) => c.toUpperCase())
	.join("\n");

if (cmd.parameter == "upper" || cmd.parameter == "lower") {
	const ch = cmd.str(
		`echo "${
			cmd.parameter == "upper" ? capitalCharacters : characters
		}" | rofi -dmenu -p "Select character" -theme ~/dotfiles/config/rofi/characters/conf.rasi`
	);

	if (!ch) cmd.exit();

	cmd.copy(ch);
	cmd.paste();
	cmd.exit();
}
