#!/bin/sh

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

icon() {

status=$(cat "$bat/status")

if [ "$per" = "100" ]; then
	[[ $status = Charging ]] && icon="󰂅" || icon="󰁹"
elif [ "$per" -gt "90" ]; then
	[[ $status = Charging ]] && icon="󰂋" || icon="󰂂"
elif [ "$per" -gt "80" ]; then
	[[ $status = Charging ]] && icon="󰂊" || icon="󰂁"
elif [ "$per" -gt "70" ]; then
	[[ $status = Charging ]] && icon="󰢞" || icon="󰂀"
elif [ "$per" -gt "60" ]; then
	[[ $status = Charging ]] && icon="󰂉" || icon="󰁿"
elif [ "$per" -gt "50" ]; then
	[[ $status = Charging ]] && icon="󰢝" || icon="󰁾"
elif [ "$per" -gt "40" ]; then
	[[ $status = Charging ]] && icon="󰂈" || icon="󰁽"
elif [ "$per" -gt "30" ]; then
	[[ $status = Charging ]] && icon="󰂇" || icon="󰁼"
elif [ "$per" -gt "20" ]; then
	[[ $status = Charging ]] && icon="󰂆" || icon="󰁻"
elif [ "$per" -gt "10" ]; then
	notify-send -u critical "Battery Low" "Connect Charger"
	[[ $status = Charging ]] && icon="󰢜" || icon="󰁺"
elif [ "$per" -gt "0" ]; then
	[[ $status = Charging ]] && icon="󰢟" || icon="󰂃"
	notify-send -u critical "Battery Low" "Connect Charger"
else
	[[ $status = Charging ]] && icon="󱉝󱐋" || icon="󱉝"
fi

echo "$icon"

}

percent() {
echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
exit