#!/bin/node
import cmd from "../../../scripts/cmd.js";
import { modi } from "./hyprland-cheatsheet";

const p = cmd.dotfilesDir + "/config/rofi/scripts/hyprland-cheatsheet";
cmd.run(
	`rofi -show common -modi "${modi
		.map((mod) => `${mod}:${p} ${mod}`)
		.join(",")}" -theme ~/dotfiles/config/rofi/hyprland-cheatsheet.rasi`
);
