
alias eza="eza --icons=always --git-ignore"
alias ezaList="eza -l -M --no-user --no-time"
alias h="Hyprland"
alias l=eza
alias ll=ezaList
alias lla="eza --icons=always -a -l -M --no-user --no-time"
alias la="eza --icons=always -a"
alias lr="$eza -T -L=3"
alias lsf="$eza -f --show-symlinks -a"
alias lsd="$eza -D --show-symlinks"
alias lls="$ezaList --total-size"
alias c="wl-copy"
alias pwdc="pwd | wl-copy"
alias pc="utils path-copy"
alias grep="grep --color=auto"
alias g="grep --color=auto"
alias gs="git status"
alias gc="git add --all git commit -m"
alias gp="git pull"
alias alert='notify-send -e --urgency=normal "Command has finished"'
alias n='notify-send -e --urgency=normal "Command has finished"'
alias cls="clear"
alias coder="code -r"
alias yt="yt-dlp -x --audio-format mp3 -P ~/Desktop/Alex/Music/"
alias f="fuck"
alias r="trash-put"
alias rr="rm -ir"
alias mocp="mocp -T nightly_theme"
alias i="~/dotfiles/scripts/install"
# alias s="sudo -Es" 
alias s="sudo -Es env \"PATH=$PATH\""
alias path="echo $PATH | tr ':' '\\n' | tv"
alias snvim="sudo -E -s nvim"
alias nvchad="exec env NVIM_APPNAME=nvim.nvchad nvim"
alias nvlazy="exec env NVIM_APPNAME=nvim.lazy nvim"
alias envn="set tmp (env | grep (tv env) | cut -d '=' -f1)commandline $tmp"
alias envv="set tmp (env | grep (tv env) | cut -d '=' -f2-)commandline $tmp"
alias pathf="echo $PATH | tr ' ' '\\n' | tv"
alias deepseek="ollama serve & ollama run deepseek-r1:1.5b"
alias +x="chmod +x"
# alias t="set tmp=(tmux capture-pane -S -1000 && tmux show-buffer | sed -e '/❯ */d' -e '/^t$/d' -e '/^$/d' -e '/^ ~ 󰮺$/d' | vipe) commandline $tmp"
alias trash-tui="~/Desktop/VSC/trash-tui/target/x86_64-unknown-linux-gnu/debug/trash-tui"
alias pi="install-arch pi"
alias yi="install-arch yi"
alias rp="install-arch rp"
