#!/bin/node

import fs from "fs";
import cmd from "../../../scripts/cmd.js";

const entries = [
	{ display: " Downloads", path: "~/Downloads" },
	{ display: "󱝏 Temp", path: "~/Downloads/temp" },
	{ display: " Desktop", path: "~/Desktop" },
	{ display: " Dotfiles", path: "~/dotfiles" },
	{ display: "󰙅 My files", path: "~/Desktop/Alex" },
	{ display: " Music", path: "~/Desktop/Alex/Music" },
	{ display: " Screenshots", path: "~/screenshots" },
	{ display: " Home", path: "~" },
	{ display: "󰨞 VSC", path: "~/Desktop/VSC" },
];

const entry = entries.find((entry) => entry.display === cmd.parameter);

if (entry) {
	fs.writeFileSync("/tmp/rofi-dir", entry.path);
	console.log("\n󰙅 File manager\n Copy\n󰨞 VS Code\n Terminal");
	cmd.exit();
}

if (cmd.parameter) {
	const data = fs.readFileSync("/tmp/rofi-dir").toString().replace("~", process.env.HOME);
	switch (cmd.parameter) {
		case "󰙅 File manager":
			cmd.spawn("xdg-open", data);
			break;
		case " Copy":
			cmd.spawn("wl-copy", data);
			break;
		case "󰨞 VS Code":
			cmd.spawn("code", data);
			break;
		case " Terminal":
			cmd.spawn("ghostty", `--working-directory=${data}`);
			break;
	}

	fs.unlinkSync("/tmp/rofi-dir");
	cmd.exit();
}

entries.forEach((entry) => console.log(`${entry.display}`));
