#!/bin/node

import cmd, { KEYS } from "../../../scripts/cmd.js";

const entries = [
	{ display: " Downloads", path: "~/Downloads" },
	{ display: "󱝏 Temp", path: "~/Downloads/temp" },
	{ display: " Desktop", path: "~/Desktop" },
	{ display: " Dotfiles", path: "~/dotfiles" },
	{ display: "󰙅 My files", path: "~/Desktop/Alex" },
	{ display: " Music", path: "~/Desktop/Alex/Music" },
	{ display: " Screenshots", path: "~/screenshots" },
	{ display: " Home", path: "~" },
	{ display: "󰨞 VSC", path: "~/Desktop/VSC" },
];

const entry = entries.find((entry) => entry.display === cmd.parameter);

if (entry) {
	cmd.set(KEYS.rofiDir, entry.path).print("\n󰙅 File manager\n Copy\n󰨞 VS Code\n Terminal").exit();
}

if (cmd.parameter) {
	const data = cmd.get(KEYS.rofiDir).replace("~", process.env.HOME);
	switch (cmd.parameter) {
		case "󰙅 File manager":
			cmd.spawn("xdg-open", data);
			break;
		case " Copy":
			cmd.spawn("wl-copy", data);
			break;
		case "󰨞 VS Code":
			cmd.spawn("code", data);
			break;
		case " Terminal":
			cmd.spawn("ghostty", `--working-directory=${data}`);
			break;
	}

	cmd.set(KEYS.rofiDir, "").exit();
}

entries.forEach((entry) => console.log(`${entry.display}`));
