#!/bin/node
import fs from "fs";
import mode from "stat-mode";

if (process.getuid() !== 0) throw "Not running with root";

const rootPath = '/dev/'
const filePattern = /(ttyS\d+)|(ACM\d+)/

function unlock(f) {
	fs.chmod(`${rootPath}${f}`, 0o777, (err) => {
		if (err) {
			throw err;
		} else {
			console.log(`unlocked ${f}`);
		}
	});
}

function shouldUnlock(f) {
	if (!filePattern.test(f) || !fs.existsSync(`${rootPath}${f}`) ) return;

	return !(new mode.Mode(fs.statSync(`${rootPath}${f}`).mode).others.write);
}

fs.watch(rootPath).on("change", (e, f) => {
	if (e === "change" &&  shouldUnlock(f))	unlock(f);
});

for (const f of fs.readdirSync(rootPath)) {
	if (shouldUnlock(f)) unlock(f);
}
