#!/bin/node

import cmd from "./cmd.js";

const sink = cmd.str("pamixer --list-sinks | grep Running | awk '{print $1}'");
const activeSink = cmd.str("pamixer --get-default-sink | grep Running | awk '{print $1}'")
if (sink && sink !== activeSink) {
  cmd.run(`pactl set-default-sink ${sink}`)
}

if (cmd.parameter === "m") {
  cmd.run("pamixer -t").exit();
}

let vol = cmd.num("pamixer --get-volume");

if (isNaN(vol)) cmd.error("cannot get volume").exit(1);

vol = Math.round(vol * 100) / 100

const isMinus = cmd.parameter === "-";
const treshold = isMinus ? 6 : 5;
const sign = isMinus ? -1 : 1;
let difference = 1;
let roundingFactor = 0;

if (vol >= treshold) {
	roundingFactor = vol % 5;
	difference = 5;

	if (roundingFactor !== 0 && isMinus) {
		roundingFactor = 5 - roundingFactor;
	}

	difference -= roundingFactor;
}

difference *= sign;
console.log(vol, difference, sign, roundingFactor)
cmd.run(`pamixer --allow-boost --set-volume ${vol + difference}`);
