#! /bin/bash

function copy_util() {
  # remove the last character, which is a newline
  echo -e $@ | head -c -1 | xsel -b
}

function copy_from_cmd() {
  res=$(eval $@)
  copy_util $res
  echo $res
}

function show_help() {
  echo "Copy utility
It copies text to the clipboard

If no flags are provided it copies the output of the provided command
ex: \`copy pwd\` -> puts the current directory in the clipnoard 

-f [FILE]
Copies the contents of a file

-r
\"(raw)\" - copies as string
ex: \`copy -r some-text\` -> puts \"some-text\" in the clipboard

<empty>
If no arguments are provided it defaults to \`copy pwd\`
"

  exit 0
}

if [[ -z $@ ]]; then
  pipeOutput="";
  while read out;
  do
    pipeOutput=$pipeOutput'\n'$out 
  done
  
  pipeOutput=${pipeOutput:2};

  if [[ -z $pipeOutput ]]; then
    copy_from_cmd pwd
    exit 0
  fi

  echo -e $pipeOutput
  copy_util $pipeOutput
  exit 0;
fi

while getopts "f:r:h:l" arg; do
  case $arg in
    f)
      if [[ -d $2 ]]; then
        echo "copy: $2: Is a directory"
        exit 1
      elif [[ ! -f $2 ]]; then
        echo "copy: $2: No such file"
        exit 1
      fi
       
      copy_util $(cat $2)

      readlink -f $2
      exit 0
      ;;
    r)
      copy_util "${@:2}"
      exit 0
      ;;
    l)
      lastCmd=$(tail ~/.local/share/fish/fish_history | grep cmd | tail -2 | head -1 | cut -c '8-')
      echo $lastCmd
      copy_util $lastCmd
      exit 0
      ;;
    h)
      show_help
      ;;
  esac
done

copy_from_cmd $@

exit 0
