#!/bin/node

import cmd from "./cmd.js";

if (cmd.isRunning("cmatrix")) cmd.exit();

const brightness = cmd.num("brightnessctl g");

for (let val = brightness; val > 0; val -= 1000) {
	cmd.wait(0.04).run(`brightnessctl s ${val}`);
}

// const pid = cmd
// 	.run(`brightnessctl s ${brightness}`)
// 	.spawn(
// 		"ghostty",
// 		"-e",
// 		"ghostty --background-opacity=1 --background=#1D1F21 --fullscreen -e cmatrix -b -C blue",
// 		"&"
// 	);

// cmd.wait(100).run(`kill ${pid}; hyprctl dispatch dpms off; hyprlock`);
cmd.run(`hyprctl dispatch dpms off; hyprlock`);
