#!/bin/node

import cmd from "./cmd.js";

const dir = cmd.parameter;

function move() {
	if (dir === "r" || dir === "l") {
		cmd.run(`~/dotfiles/scripts/change-workspace ${dir === "r" ? "next" : "prev"}`);
	} else {
		cmd.run(`hyprctl dispatch focusmonitor ${dir === "u" ? "+1" : "-1"}`);
	}
}

const prevWindow = JSON.parse(cmd.str(`hyprctl activewindow -j`));
cmd.run(`hyprctl dispatch "hy3:movefocus ${dir}"`);

const currWindow = JSON.parse(cmd.str(`hyprctl activewindow -j`));

if (!currWindow.pid) {
	move();
	cmd.exit();
}

if (prevWindow.pid !== currWindow.pid || prevWindow.title !== currWindow.title) cmd.exit();

if (currWindow.workspace.name.startsWith("special")) {
	cmd.run(`~/dotfiles/scripts/close-special-workspace.sh`);
	cmd.exit();
}

move();
