#!/bin/node

import cmd from "./cmd.js";

let dir = cmd.params[0];

const prevWindow = JSON.parse(cmd.str(`hyprctl activewindow -j`));

cmd.run(`~/dotfiles/scripts/close-special-workspace.sh && hyprctl dispatch "hy3:movefocus ${dir}"`);

const currWindow = JSON.parse(cmd.str(`hyprctl activewindow -j`));

if (prevWindow.pid === currWindow.pid && prevWindow.title === currWindow.title) {
	if (dir === "r" || dir === "l") {
		cmd.run(`~/dotfiles/scripts/change-workspace ${dir === "r" ? "next" : "prev"}`);
	} else {
		cmd.run(`hyprctl dispatch workspace ${dir === "u" ? "+m" : "-m"}`);
	}
}
