#!/bin/node

import fs from "fs";
import path from "path";
import cmd from "./cmd.js";
import { removePackage } from "./uninstall";

function createTopic() {
	const newTopic = cmd.prompt("Enter new topic:", { color: "cyan" });
	if (!newTopic) cmd.exit();

	cmd.print(`Creating new topic: ${newTopic}`, { color: "greenBright", bold: true });
	const varName = newTopic.replace(/\s/g, "_");
	const defaultNix = cmd.read(path.resolve(packagesDir, "default.nix"));
	cmd.writeTo(
		path.resolve(packagesDir, "default.nix"),
		defaultNix
			.replace("in with pkgs;", `  ${varName} = import ./${newTopic}.nix;\nin with pkgs;`)
			.replace("[", `${varName} { pkgs = pkgs; } ++ [`)
	);

	cmd.writeTo(path.resolve(packagesDir, `${newTopic}.nix`), "{ pkgs }:\n\nwith pkgs; [\n]");

	return newTopic;
}

function graceFulExit() {
	if (isCreatintNewTopic) {
		removeTopic(topic);
	} else {
		packages.forEach((pkg) => removePackage(topic, pkg));
	}
}

let isCreatintNewTopic = false;
const packagesDir = path.resolve(cmd.dotfilesDir, "nix", "packages");
const topicOptions = fs
	.readdirSync(packagesDir)
	.filter((topic) => topic !== "default.nix")
	.map((topic) => topic.replace(".nix", ""))
	.concat("<new topic>");

let topic = cmd.fzf(topicOptions);
if (!topic) cmd.print("No topic selected", { color: "gray" }).exit();

if (topic === "<new topic>") {
	cmd.print("Creating new topic", { color: "blue" });
	isCreatintNewTopic = true;
	topic = createTopic();
} else {
	cmd.print("Using topic: " + topic, { color: "blue" });
}

const packages = cmd.prompt("Enter package(s):", { color: "cyan" }).split(/\s+/);
if (packages.length === 0) cmd.print("No packages entered", { color: "gray" }).exit();

const packagesFile = cmd.read(path.resolve(packagesDir, `${topic}.nix`));
cmd.writeTo(path.resolve(packagesDir, `${topic}.nix`), packagesFile.replace("[", `[\n  ${packages.join("\n  ")}`));

cmd.print(`Installing package${packages.length > 1 ? "s" : ""} ${packages.join(", ")} in "${topic}"`, {
	color: "greenBright",
	bold: true,
});

process.on("SIGINT", function () {
	cmd.error("Caught interrupt signal");
	graceFulExit();
	cmd.exit(1);
});

if (cmd.run("home-manager switch")) {
	cmd.notify(`${packages.join(", ")} downloaded`);
	cmd.print("Done", { color: "blueBright", bold: true });
} else {
	graceFulExit();
}
