#!/bin/node
import cmd from "./cmd.js";

const val = cmd.str("cliphist list | rofi -i -dmenu -theme ~/dotfiles/config/rofi/clipboard.rasi | cliphist decode");

if (val) {
	cmd.copy(val);
	cmd.paste();
}
