#!/bin/bash

#!/bin/sh

# Set the directory where wallpapers are stored
WALLPAPER_DIR="$HOME/dotfiles/assets/hypr"

# Check if the directory exists
if [ ! -d "$WALLPAPER_DIR" ]; then
  echo "Error: Wallpaper directory does not exist: $WALLPAPER_DIR"
  exit 1
fi

# Find all image files and choose one randomly
RANDOM_WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' -o -iname '*.webp' \) | shuf -n 1)

# Check if a file was found
if [ -z "$RANDOM_WALLPAPER" ]; then
  echo "Error: No wallpapers found in $WALLPAPER_DIR"
  exit 1
fi

swaybg -i $RANDOM_WALLPAPER -m fit
