#!/bin/node

import fs from "fs";
import path from "path";
import cmd from "./cmd.js";

const WALLPAPER_DIR = path.join(cmd.dotfilesDir, "assets", "hypr");

if (!fs.existsSync(WALLPAPER_DIR)) {
	cmd.error(`Error: Wallpaper directory does not exist: ${WALLPAPER_DIR}`).exit(1);
}

const wallpapers = fs.readdirSync(WALLPAPER_DIR);
const wallpaper = path.join(
	cmd.dotfilesDir,
	"assets",
	"hypr",
	wallpapers[Math.round(Math.random() * (wallpapers.length - 1))]
);

if (!fs.existsSync(wallpaper)) {
	cmd.error(`Error: No wallpapers found in: ${WALLPAPER_DIR}`).exit(1);
}

const waybarCSSPath = path.join(cmd.dotfilesDir, ".config", "waybar", "style.css");
const waybarCSS = cmd.read(waybarCSSPath).split("\n");
const bgLineIndex = waybarCSS.findIndex((line) => line.includes("scripts/set-wallpaper"));
if (wallpaper.endsWith("/view-rock-formations-with-nature-landscape.jpg")) {
	waybarCSS[bgLineIndex] = waybarCSS[bgLineIndex].replace(/alpha\(.*\)/, "alpha(#000000, 0.2)");
} else {
	waybarCSS[bgLineIndex] = waybarCSS[bgLineIndex].replace(/alpha\(.*\)/, "alpha(#000000, 0)");
}
cmd.writeTo(waybarCSSPath, waybarCSS.join("\n"));

cmd.run(`swaybg -i "${wallpaper}" -m fill`);
