#!/bin/node
import cmd from "./cmd.js";

// close special workspace on focused monitor if one is present

if (cmd.isRunning("open-special")) cmd.exit();

const workspace = cmd
	.json("hyprctl -j monitors")
	.find((monitor) => monitor.focused)
	.specialWorkspace.name.replace("special:", "");

if (workspace) {
	cmd.writeTo("/tmp/last-special-workspace", workspace).run(`hyprctl dispatch togglespecialworkspace "${workspace}"`);
} else {
	cmd.run(`open-special "${cmd.read("/tmp/last-special-workspace")}" g`);
}
