#!/bin/node
import cmd, { KEYS } from "./cmd.js";

// toggle special workspace on focused monitor if one is present

if (cmd.isRunning("open-special")) cmd.exit();

const workspace = cmd
	.json("hyprctl -j monitors")
	.find((monitor) => monitor.focused)
	.specialWorkspace.name.replace("special:", "");

if (workspace) {
	cmd.set(KEYS.lastWorkspace, workspace).run(`hyprctl dispatch togglespecialworkspace "${workspace}"`);
} else if (cmd.parameter !== "close") {
	cmd.run(`~/scripts/open-special "${cmd.get(KEYS.lastWorkspace)}" g`);
}
