#!/bin/node

import fs from "fs";
import cmd from "../../../scripts/cmd.js";

if (cmd.params[0]) {
	// cmd.run(`xdg-open ${cmd.params[0]}`);
	cmd.run(`wl-copy ${cmd.params[0]}`);
	cmd.run("pkill rofi");
	cmd.exit();
} else {
	cmd.run("cp ~/.config/google-chrome/Default/History /tmp/chrome-data.sql");
	cmd.run(
		`sqlite3 /tmp/chrome-data.sql "select datetime(last_visit_time/1000000-11644473600,'unixepoch'),url from  urls order by last_visit_time desc LIMIT 1000" | cut -d '|' -f2 | | tr -d 'https://' > /tmp/chrome-hist-urls`
	);
	console.log(fs.readFileSync("/tmp/chrome-hist-urls").toString());
}
