#!/bin/node

import fs from "fs";
import cmd, { copy, paste } from "../../../scripts/cmd.js";

const copyText = " Copy";
const openText = "󰇯 Open";

const entries = [
	["Fontys", "https://outlook.office.com/mail/", "Outlook", "aleksandar.popov@student.fontys.nl"],
	["alexphone33@gmail.com", "https://mail.google.com/mail/u/0", "Gmail"],
	["alexander.popov233@gmail.com", "https://mail.google.com/mail/u/1", "Gmail"],
	["alp7569@gmail.com", "https://mail.google.com/mail/u/2", "Gmail"],
];

const entry = entries.find((entry) => entry[0] === cmd.parameter);

if (entry) {
	fs.writeFileSync("/tmp/rofi-email", entry[1]);
	console.log(`\n${copyText}\n${openText}\n`);
	cmd.exit();
}

if (cmd.parameter) {
	const address = fs.readFileSync("/tmp/rofi-email").toString();
	switch (cmd.parameter) {
		case copyText:
			let email = entries.find((entry) => entry[1] === address)[0];
			if (email === "Fontys") email = entries[0][3];
			copy(email);
			paste();
			break;
		case openText:
			cmd.run(`xdg-open "${fs.readFileSync("/tmp/rofi-email").toString()}"`);
			break;
	}

	fs.unlinkSync("/tmp/rofi-email");
	cmd.exit();
}

entries.forEach((entry) => cmd.print(`${entry[0]}\x00icon\x1f${cmd.dotfilesDir}/config/rofi/icons/${entry[2]}.ico`));
