#!/bin/node

import fs from "fs";
import cmd from "../../../scripts/cmd.js";

const entries = [
	["Fontys", "https://outlook.office.com/mail/", "Outlook"],
	["alexphone33@gmail.com", "https://mail.google.com/mail/u/0", "Gmail"],
	["alexander.popov233@gmail.com", "https://mail.google.com/mail/u/1", "Gmail"],
	["alp7569@gmail.com", "https://mail.google.com/mail/u/2", "Gmail"],
];

const entry = entries.find((entry) => entry[0] === cmd.parameter);

if (entry) {
	fs.writeFileSync("/tmp/rofi-email", entry[1]);
	console.log("\n Copy\n󰇯 Open\n");
	cmd.exit();
}

if (cmd.parameter) {
	cmd.notify(cmd.parameter);
	const address = fs.readFileSync("/tmp/rofi-email").toString();
	if (cmd.params[0].includes("Copy")) {
		let email = entries.find((entry) => entry[1] === address)[0];
		if (email === "Fontys") email = "aleksandar.popov@student.fontys.nl";

		cmd.run(`wl-copy "${email}"`);
	} else if (cmd.params[0].includes("Open")) {
		cmd.run(`xdg-open "${fs.readFileSync("/tmp/rofi-email").toString()}"`);
	}

	fs.unlinkSync("/tmp/rofi-email");
	cmd.exit();
}

entries.forEach((entry) => cmd.print(`${entry[0]}\x00icon\x1f${cmd.dotfilesDir}/config/rofi/icons/${entry[2]}.ico`));
