#!/bin/node

import cmd, { KEYS } from "../../../scripts/cmd.js";

const copyText = " Copy";
const openText = "󰇯 Open";

const entries = [
	["Fontys", "https://outlook.office.com/mail/", "Outlook", "aleksandar.popov@student.fontys.nl"],
	["Tue", "https://outlook.office.com/mail/", "Outlook", "a.l.popov@student.tue.nl"],
	["alexphone33@gmail.com", "https://mail.google.com/mail/u/0", "Gmail"],
	["alp7569@gmail.com", "https://mail.google.com/mail/u/1", "Gmail"],
	["alexander.popov233@gmail.com", "https://mail.google.com/mail/u/2", "Gmail"],
];

const entry = entries.find((entry) => entry[0] === cmd.parameter);

if (entry) {
	cmd.set(KEYS.email, entry[1]).print(`\n${copyText}\n${openText}\n`).exit();
}

if (cmd.parameter) {
	const address = cmd.get(KEYS.email);
	switch (cmd.parameter) {
		case copyText:
			let email = entries.find((entry) => entry[1] === address)[0];
			if (email === "Fontys") email = entries[0][3];
			cmd.copy(email);
			cmd.paste();
			break;
		case openText:
			cmd.run(`xdg-open "${address}"`);
			break;
	}

	cmd.set(KEYS.email, "").exit();
}

entries.forEach((entry) => cmd.print(`${entry[0]}\x00icon\x1f${cmd.dotfilesDir}/config/rofi/icons/${entry[2]}.ico`));
